development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:66ce2bb51b0b02689a76a33c4fff81ee@scat.redistogo.com:11609/
  # channel_prefix: slack_clone_production
